service: fastpi-aws-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-west-1

package:
  individually: true
  patterns:
    - "!requirements.txt"

layers:
  fastApi:
    path: fastApi
    name: fastApi
    description: lambda layer for fastapi related dependencies
    compatibleRuntimes:
      - python3.9
    retain: false

functions:
  users:
    handler: challenge.api.handler
    layers:
      - !Ref FastApiLambdaLayer 
    url: true  