name: "Continuous Integration"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: run model tests
        run: |
          pytest --cov-config=.coveragerc tests/model
      - name: run api tests
        run: |
          pytest --cov-config=.coveragerc tests/api

