name: "Continuous Integration"

on:
  push:
    branches: ["ci_test"]
  pull_request:
    branches: ["ci_test"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: run model tests
        run: |
          make model-test
      - name: run api tests
        run: |
          make api-test
